package com.llycloud.lms.constants;

/**
 * @author Akide Liu
 * @date 2021-01-28 22:34
 */
public class SecurityConstants {

    /**
     * The Authorization api endpoint
     */
    public static final String AUTH_LOGIN_URL = "/auth/login";

    /**
     * jwt secret key
     * generated by https://www.allkeysgenerator.com/ use 512-bit algorithm
     */
    public static final String JWT_SECRET_KEY = "w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E(H+MbQeThWmZq";

    /**
     * The token prefix inside of http Authorization header
     */
    public static final String TOKEN_PREFIX = "Bearer ";

    public static final String TOKEN_HEADER = "Authorization";

    public static final String TOKEN_TYPE = "JWT";

    public static final String TOKEN_ROLE_CLAIM = "role";
    public static final String TOKEN_ISSUER = "security";
    public static final String TOKEN_AUDIENCE = "security-all";


    /**
     * The general login will place the token valid for 2 hours
     *
     * WithOUT remember field
     */
    public static final long EXPIRATION_TIME = 60 * 60 * 2L;


    /**
     * The remember me login will place the token valid for 7 days
     *
     * With remember filed
     */
    public static final long EXPIRATION_REMEMBER_TIME = 60 * 60 * 24 * 7L;


}
